123-Validate-Phone-Number (resolves #123)
hack4impact-calpoly/habitat-for-humanity pull request #149
Opened 2023-02-08 02:30 UTC by ZealSV

## Developer: Muzart Tuman

### Pull Request Summary

Fixed issue #123 Validate Phone Number by fixing the processPhoneNumber() function. I added a phone number length parameter which makes sure the phone number you input is the correct amount of digits.

### Pull Request Checklist

- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [x] The developer name is specified
- [x] The summary is completed
- [x] Ask for a review in communication channels

### Reviewer Checklist - PULL REQUEST REVIEWER ONLY

IMPORTANT: The rest of the sections in this checklist should only be filled out by authorized pull request reviewers. If you are the individual contributor, do not fill out the rest of the fields or check the boxes.

## Reviewer: Full Name

NOTE: Pull requests should only be merged when all boxes are checked.

- [ ] Assign yourself as reviewer if not assigned
- [ ] The reviewer name is specified
- [ ] The code is fully reviewed
- [ ] Meaningful feedback is given
- [ ] Let developer know a review has been made

2023-02-21 03:30 UTC, ObjectJosh commented
@scallait

2023-02-23 02:02 UTC, scallait requested changes
1. Error Message should disappear once a valid phone number is typed in
<img width="326" alt="image" src="https://user-images.githubusercontent.com/71291167/220802426-abb43f44-1f77-47ca-9f47-7e6fe6794b47.png">

2023-02-23 02:02 UTC, scallait commented on frontend/src/components/authentication/CreateAccountPage/CreateAccountPage.tsx
> +      }
This is unnecessary as isMobilePhone() already checks for length

2023-03-09 00:27 UTC, scallait approved these changes

2023-03-09 00:29 UTC, merged