addedforgotPasswordPage
hack4impact-calpoly/habitat-for-humanity pull request #38
Opened 2022-01-18 03:21 UTC by ObjectJosh

2022-01-18 03:28 UTC, ObjectJosh commented on frontend/src/components/ForgotPasswordPage/ForgotPasswordPage.css
> +    padding: 0px;
```suggestion
    padding: 9px;
```
Just adding some padding:
<img width="554" alt="Screen Shot 2022-01-17 at 7 27 57 PM" src="https://user-images.githubusercontent.com/42549561/149865885-e4c7d631-350f-445c-b9ee-69a0c9898cd1.png">

2022-01-18 04:18 UTC, tessa-tapmongkol requested changes

2022-01-18 04:18 UTC, tessa-tapmongkol commented on frontend/src/components/ForgotPasswordPage/ForgotPasswordPage.css
> +}
Add css for smaller view ports. You can do this by using `@media only screen and (max-width: ) { }` or  `@media only screen and (max-height: ) { }` 
For example, to change the width of #forgotPasswordBox at up to 500px you would do:
`@media only screen and (max-width: 500px) {
    #forgotPasswordBox {
        width: 200px
    }
}`
And you can use this for even smaller viewports.

2022-01-18 04:18 UTC, tessa-tapmongkol commented on frontend/src/components/ForgotPasswordPage/ForgotPasswordPage.css
> +    color: var(--black);
nit: the color on Figma is an off black (#011338) not sure how much this matters

2022-01-20 06:00 UTC, closed without merging

2022-01-20 06:01 UTC, ObjectJosh commented
3-Forgot-Password-Page-Fixes